print ("Tugas Python")
print ()
nama = input("Masukan Nama Anda :")
pgln = input("Masukan Panggilan :")
nim = input("Masukan NIM :")
tglhr = input("Masukan Tanggal Lahir :")
tmlhr = input("Masukan Tempat Lahir :")
tlpn = input("Masukan Telepon :")
almt = input("Masukan Alamat :")
umur = input("Masukan Umur Anda :")
print ()
print ("Assalamu'alaikum wr. wb.")
print ()
print ("Izinkan saya memperkenlkan diri saya. nama saya",nama,"Tapi anda bisa memanggil saya",pgln,
       "NIM saya",nim,"Saya Lahir di",tmlhr,"dan Saya Berumur",umur,"tahun. Tempat tinggal saya di",almt,
       ". Jadi, jika ada perlu silahkan hubungi saya dengan nomor",tlpn,)
print ()
print ("Terima Kasih")
print ("Wassalamu'alaikum wr. wb.")
